/**
 * Auto generated by Dubbo2Ts.
 *
 * Wed Nov 15 2017 11:31:28 GMT+0800 (CST)
 */

import Dubbo from "dubbo-node-zookeeper";

export const ServiceHead = {
    interfac: "com.alibaba.dubbo.demo.DemoService",
    version: "LATEST",
    timeout: 6000,
    group: "dubbo",
    methods: {
        sayHello: name => [{ $class: "java.lang.String", $: name }],
        sayHello2: req => [
            { $class: "com.alibaba.dubbo.demo.DemoReq", $: req }
        ],
        sayHello3: (name, age) => [
            { $class: "java.lang.String", $: name },
            { $class: "java.lang.Integer", $: age }
        ]
    }
};

export function sayHello(name: string) {
    return Dubbo.exec<string>("DemoService.sayHello", name);
}

export function sayHello2(req: any) {
    return Dubbo.exec<string>("DemoService.sayHello2", req);
}

export function sayHello3(name: string, age: number) {
    return Dubbo.exec<string>("DemoService.sayHello3", name, age);
}

export default {
    sayHello,
    sayHello2,
    sayHello3
};
