"use strict";
/**
 * Auto generated by Dubbo2Ts.
 *
 * Wed Nov 29 2017 17:53:09 GMT+0800 (CST)
 */
Object.defineProperty(exports, "__esModule", { value: true });
var DemoService_1 = require("./DemoService");
exports.default = {
    DemoService: DemoService_1.ServiceHead
};
