"use strict";
/**
 * Auto generated by Dubbo2Ts.
 *
 * Wed Nov 15 2017 00:47:11 GMT+0800 (CST)
 */
Object.defineProperty(exports, "__esModule", { value: true });
var DemoService_1 = require("./DemoService");
exports.default = {
    DemoService: DemoService_1.ServiceHead
};
