/**
 * Auto generated by Dubbo2Ts.
 *
 * Wed Nov 15 2017 13:28:04 GMT+0800 (CST)
 */

import Dubbo from "dubbo-node-zookeeper";

export const ServiceHead = {
    interfac: "com.alibaba.dubbo.demo.DemoService",
    version: "LATEST",
    timeout: 6000,
    group: "dubbo",
    methods: {
        sayHello: name => [{ $class: "java.lang.String", $: name }],
        sayHello2: req => [{ $class: "com.alibaba.dubbo.demo.DemoReq", $: req }]
    }
};

export function sayHello(name: string) {
    return Dubbo.exec<string>("DemoService.sayHello", name);
}

export function sayHello2(req: any) {
    return Dubbo.exec<string>("DemoService.sayHello2", req);
}

export default {
    sayHello,
    sayHello2
};
